### ISSUE TITLE
Meta Considerations For Issues And Discussions

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [AFg6K7h4fhy2/Forecasting-Tornadoes#4]
## Goal

Add checklist of issues & discussions that should be created to facilitate tornado forecasting and the use of best practices in software development, statistics, and forecasting.

## Context

See Goal.

## Tasks

- [ ] Mathematical Approaches For Forecasting Tornados (discussion)
- [ ] Existing Work On Tornado Forecasting (discussion)
- [ ] Best Practices In Repository's Software And Model Design (issue and discussion)
- [ ] Model Diagrams Creation (issue)
- [ ] Data Visualization Checklist (issue and discussion)
- [ ] Samples Saving Scheme (issue and discussion)
- [ ] Forecast Saving Scheme (issue and discussion)
- [ ] Config Default Values (issue)
- [ ] Model Naming And Lead Models (discussion)
- [ ] Sensitivity Analysis (issue)
- [ ] Model Documentation (issue)
- [ ] Converting Forecasts To Metaculus Predictions (issue)

## Out Of Scope

TBD.

## Resources & Links

TBD.
